#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
import os
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
NOTES_PATH = ROOT / "docs" / "agent_contract.notes.md"
INTEGRATION_PATH = ROOT / "docs" / "agent_integration.md"


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip() or "-"


def _action_label(action: argparse.Action, *, one_required: bool = False) -> str:
    if action.option_strings:
        label = ", ".join(action.option_strings)
        if action.required:
            label += " (required)"
        elif one_required:
            label += " (one required)"
        return label
    suffix = "" if action.nargs in (None, 1) else f" [{action.nargs}]"
    return f"{action.dest}{suffix}"


def _twin_cli_rows() -> list[tuple[str, str, str]]:
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from scripts.twin.__main__ import EXPORTED_COMMAND_VISIBILITIES, build_parser

    parser = build_parser()
    subparsers = next(
        action for action in parser._actions if isinstance(action, argparse._SubParsersAction)
    )
    rows: list[tuple[str, str, str]] = []
    for name, command_parser in sorted(subparsers.choices.items()):
        visibility = getattr(command_parser, "twin_visibility", None)
        if visibility is None:
            raise ValueError(f"twin command {name!r} is missing explicit visibility")
        if visibility not in EXPORTED_COMMAND_VISIBILITIES:
            continue
        positionals: list[str] = []
        options: list[str] = []
        one_required = {
            action
            for group in command_parser._mutually_exclusive_groups
            if group.required
            for action in group._group_actions
        }
        for action in command_parser._actions:
            if isinstance(action, argparse._HelpAction):
                continue
            target = options if action.option_strings else positionals
            target.append(_action_label(action, one_required=action in one_required))
        rows.append((f"twin {name}", ", ".join(positionals), ", ".join(options)))
    return rows


def _slash_surface() -> str:
    source = (ROOT / "commands" / "twin.md").read_text(encoding="utf-8")
    match = re.search(r"^## 用户命令面\s+```text\n(.*?)\n```", source, re.MULTILINE | re.DOTALL)
    if not match:
        raise ValueError("commands/twin.md is missing the generated user command surface block")
    return match.group(1).strip()


def _schema_rows() -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for path in sorted((ROOT / "schemas").glob("twin.*.schema.json")):
        value = json.loads(path.read_text(encoding="utf-8"))
        required = value.get("required") if isinstance(value, dict) else []
        rows.append((path.name, str(value.get("title") or ""), ", ".join(required or [])))
    return rows


def render_generated() -> str:
    lines = [
        "<!-- GENERATED by scripts/export_agent_contract.py. DO NOT EDIT. -->",
        "# Agent Contract",
        "",
        "## Claude Command Surface",
        "",
        "Source: `commands/twin.md`.",
        "",
        "```text",
        _slash_surface(),
        "```",
        "",
        "## Twin CLI",
        "",
        "Source: `global/bin/twin` and `scripts/twin/__main__.py::build_parser`.",
        "",
        "| Command | Positionals | Options |",
        "| --- | --- | --- |",
    ]
    lines.extend(f"| `{_cell(command)}` | {_cell(positionals)} | {_cell(options)} |" for command, positionals, options in _twin_cli_rows())
    lines.extend([
        "",
        "## Twin Artifact Schemas",
        "",
        "| Schema | Title | Required Top-Level Fields |",
        "| --- | --- | --- |",
    ])
    lines.extend(f"| `{name}` | {_cell(title)} | {_cell(required)} |" for name, title, required in _schema_rows())
    lines.append("")
    return "\n".join(lines)


def render_integration(generated: str, notes: str) -> str:
    notes_body = notes.strip()
    if notes_body.startswith("# ") and "\n" in notes_body:
        notes_body = notes_body.split("\n", 1)[1].strip()
    return (
        "<!-- GENERATED by scripts/export_agent_contract.py. DO NOT EDIT. -->\n"
        "# Agent Integration\n\n"
        + generated.split("# Agent Contract\n", 1)[1].strip()
        + "\n\n## Manual Notes\n\n"
        + notes_body
        + "\n"
    )


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(text, encoding="utf-8")
    os.replace(temporary, path)


def _check(path: Path, expected: str) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    if actual == expected:
        return True
    print(f"agent contract drift: {path.relative_to(ROOT)}", file=sys.stderr)
    print(
        "".join(
            difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(path),
                tofile="generated",
            )
        ),
        file=sys.stderr,
    )
    return False


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate agent-facing CLI and artifact contracts.")
    parser.add_argument("--check", action="store_true", help="Fail without writing when generated docs drift")
    args = parser.parse_args(argv)

    if not NOTES_PATH.exists():
        print(f"missing manual notes: {NOTES_PATH}", file=sys.stderr)
        return 2
    generated = render_generated()
    integration = render_integration(generated, NOTES_PATH.read_text(encoding="utf-8"))
    outputs = ((INTEGRATION_PATH, integration),)
    if args.check:
        valid = all([_check(path, text) for path, text in outputs])
        if not valid:
            print("Run: python3 scripts/export_agent_contract.py", file=sys.stderr)
        return 0 if valid else 1
    for path, text in outputs:
        _atomic_write(path, text)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
